input {
    kb_layout = us
    kb_options = fkeys:basic_13-24
}

# Program variables in ~/hyprcustom/programs.conf
#      MODS,        key,        dispatcher,             args
# app shortcuts
bind = SUPER,       Return,     exec,                   $terminal
bind = SUPER,       E,          exec,                   $files
bind = SUPER,       SUPER_L,    exec,                   hyprlauncher # why do i have to say its super+super_l this is literally one key
bind = SUPER,       R,          exec,                   hyprland-run

# complex app shortcuts (scripty)
bind = SUPER_SHIFT, S,          exec,                   grim -g "$(slurp)" - | wl-copy

# window interaction
bind = SUPER,       Q,          killactive, # pseudo-alt+f4
bind = SUPER_ALT,   Space,      togglefloating,
bind = SUPER,       Space,      pseudo,     # dwindle "fake floating"
bind = SUPER_SHIFT, Slash,      layoutmsg,              togglesplit # rotate split line
bind = SUPER,       Left,       movefocus,              l
bind = SUPER,       Right,      movefocus,              r
bind = SUPER,       Up,         movefocus,              u
bind = SUPER,       Down,       movefocus,              d
bind = SUPER,       semicolon,  layoutmsg,              splitratio -0.1
bind = SUPER,       apostrophe, layoutmsg,              splitratio +0.1
bind = SUPER,       F,          fullscreen,             0
bind = SUPER_SHIFT, F,          fullscreenstate,        0 2 # fake fullscreen for apps that lie to you

# workspace interactionsss
bind = SUPER,       Next,       workspace,              r+10
bind = SUPER,       Prior,      workspace,              r-10
bind = SUPER_CTRL,  Right,      workspace,              r+1
bind = SUPER_CTRL,  Left,       workspace,              r-1
bind = SUPER_ALT,   S,          movetoworkspace,        special:scratch
bind = SUPER,       S,          togglespecialworkspace, scratch

# media keys
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
