# This is an example Hyprland config file.
# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

# Please note not all available settings / options are set here.
# For a full list, see the wiki

# You can split this configuration into multiple files
# Create your files separately and then link them to this file like this:
# source = ~/.config/hypr/myColors.conf

$HYPR_CONF_DIR = ~/.config/hypr

# MONITOR CONFIG
source = $HYPR_CONF_DIR/monitors.conf

# PROGRAM CONFIG
source = $HYPR_CONF_DIR/programs.conf

# ENV
source = $HYPR_CONF_DIR/style/theme.conf
source = $HYPR_CONF_DIR/env.conf

# PERMISSIONS
source = $HYPR_CONF_DIR/permissions.conf

# WINDOW
source = $HYPR_CONF_DIR/style/tiling.conf
source = $HYPR_CONF_DIR/style/decor.conf
source = $HYPR_CONF_DIR/style/animation.conf
source = $HYPR_CONF_DIR/rules/window-rules.conf

# WORKSPACE
source = $HYPR_CONF_DIR/rules/workspace-rules.conf

# LAYOUT
source = $HYPR_CONF_DIR/rules/layout/dwindle.conf
source = $HYPR_CONF_DIR/rules/layout/master.conf
source = $HYPR_CONF_DIR/rules/layout/scrolling.conf
source = $HYPR_CONF_DIR/rules/layout/monocle.conf

# INPUT
source = $HYPR_CONF_DIR/input/keyboard.conf
source = $HYPR_CONF_DIR/input/mouse.conf

general {
    allow_tearing = true
}

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}
