# TODO
# GENERAL
$wall = ~/.config/hypr/wallpaper.jxl

general {
    disable_loading_bar = false
    hide_cursor = true
    immediate_render = true
}

animation = fadeIn, 0, 1, bezier
animation = fade, 1, 1, bezier


# BACKGROUND
background {
    monitor =
    path = $wall
    blur_passes = 3
}

# PASSWORD FIELD
input-field {
    monitor =
    size = 200, 50
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = false
    outer_color = rgba(30, 30, 46, 128)
    inner_color =rgba(24, 24, 37, 128)
    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    placeholder_text =
    hide_input = false
    halign = center
    valign = center
}
