# Variables
$terminal = kitty
$files = dolphin
$settings = systemsettings

# Autostart
exec-once = hyprlauncher -d
exec-once = cliphist wipe # auto clear clipboard history on reboot
exec-once = wl-paste --watch cliphist store

binds {
    movefocus_cycles_groupfirst = true
}
