# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/

windowrule {
    name = no-border-when-alone
    match:workspace=w[tv1]

    border_size = 0
    rounding = 0
}
windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}
windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}
